[package]
name = "wgpu-template"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1"
egui = "0.34"
egui-wgpu = "0.34"
egui-winit = { version = "0.34", default-features = false }
env_logger = "0.11"
log = "0.4"
pollster = "0.4"
wgpu = "29"
winit = { version = "0.30", features = ["android-native-activity"] }
wesl = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "1"
wgpu = { version = "29", features = ["webgl"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-time = "1"

[build-dependencies]
wesl = "0.3"
